/**
 * Generated tool inventory for README.md.
 *
 *   bun run tools:table          # rewrite the block between the markers
 *   bun run tools:table --check  # exit 1 if README is stale (CI / smoke test)
 *
 * The block lists every registered tool with its title and safety hints so the
 * count and names can't drift from the code. Prose grouping stays hand-written
 * below the block.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "../src/server";
import { toolRegistry, type ToolRecord } from "../src/lib";

export const BEGIN = "<!-- tools:begin (generated by `bun run tools:table`) -->";
export const END = "<!-- tools:end -->";

const HINTS: Array<[keyof ToolRecord["annotations"], string]> = [
  ["readOnlyHint", "read-only"],
  ["destructiveHint", "destructive"],
  ["idempotentHint", "idempotent"],
  ["openWorldHint", "open-world"],
];

function hintsOf(tool: ToolRecord): string {
  const on = HINTS.filter(([key]) => tool.annotations[key] === true).map(([, label]) => label);
  if (on.length > 0) return on.join(", ");
  // Explicit readOnlyHint/destructiveHint: false — mutates state, but not destructively.
  return "writes";
}

/** Markdown for the generated block, markers included. */
export function renderToolsBlock(tools: ToolRecord[] = toolRegistry): string {
  const rows = [...tools].sort((a, b) => a.name.localeCompare(b.name));
  const lines = [
    BEGIN,
    `## Tools (${rows.length})`,
    "",
    "| Tool | Title | Hints |",
    "| --- | --- | --- |",
    ...rows.map((t) => `| \`${t.name}\` | ${t.annotations.title ?? ""} | ${hintsOf(t)} |`),
    END,
  ];
  return lines.join("\n");
}

/** README with the generated block replaced (markers must already exist). */
export function spliceReadme(readme: string, block: string): string {
  const start = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (start < 0 || end < 0 || end < start) {
    throw new Error(`README.md is missing the ${BEGIN} / ${END} markers`);
  }
  return readme.slice(0, start) + block + readme.slice(end + END.length);
}

export const README_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../README.md");

if (import.meta.main) {
  createServer();
  const current = await readFile(README_PATH, "utf8");
  const next = spliceReadme(current, renderToolsBlock());
  if (process.argv.includes("--check")) {
    if (next !== current) {
      console.error("mcp/README.md tool table is stale — run `bun run tools:table`");
      process.exit(1);
    }
    console.log(`mcp/README.md tool table is current (${toolRegistry.length} tools)`);
  } else {
    await writeFile(README_PATH, next);
    console.log(`wrote ${toolRegistry.length} tools to ${README_PATH}`);
  }
}
